#     ____ _               _  ___  ____
#    / ___| |__   __ _  __| |/ _ \/ ___|
#   | |   | '_ \ / _` |/ _` | | | \___ \
#   | |___| | | | (_| | (_| | |_| |___) |
#    \____|_| |_|\__,_|\__,_|\___/|____/
#    https://github.com/NewDawn0/ChadOS
# 
#   @Author: NewDawn0
#   @Contributors: -
#   @License: MIT
#   
#   File: Makefile.toml
#   Desc: Makefile / Build instructions

env_files = ["./build-cfg/make.env"]

[tasks.default]
alias = "help"

[tasks.clean]
clear = true
script_runner = "@shell"
script = '''
cargo clean
'''

[tasks.pre-build]
clear = true
private = true
script_runner = "@shell"
script = '''
rm -rf .build ${IMG_NAME}
mkdir .build
qemu-img create .build/${IMG_NAME} 100M
'''


[tasks.build]
clear = true
dependencies = ["pre-build", "build-rs", "post-build", "build-img"]
command = "mv"
args = [".build/${IMG_NAME}", "${IMG_NAME}"]

[tasks.build-rs]
clear = true
private = true
command = "cargo"
args = ["bootimage", "--release", "--config", ".cargo/config.toml"]

[tasks.build-img]
clear = true
private = true
command = "dd"
args = [
  "conv=notrunc",
  "if=./target/x86-64/release/bootimage-ChadOS.bin",
  "of=./.build/${IMG_NAME}",
]

[tasks.post-build]
clear = true
private = true
script_runner = "@shell"
script = '''
strip ./target/x86-64/release/bootimage-ChadOS.bin
'''

[tasks.test]
clear = true
command = "cargo"
args = ["test"]

[tasks.help]
clear = true
script_runner = "@shell"
script = '''
echo 'USAGE:'
echo '  cargo make <task>'
echo
echo 'Available tasks'
echo '  run      Runs the OS in qemu'
echo '  help     Prints this menu'
echo '  test     Runs the test suite'
echo '  build    Builds the OS to a disk image'
'''

[tasks.run]
clear = true
dependencies = ["build"]
command = "qemu-system-x86_64"
args = ["-drive", "format=raw,file=ChadOS.img"]
